name: mtsp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - black=19.10b0
  - blas=1.0
  - bleach=4.0.0
  - brotli=1.0.9
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - click=8.0.3
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipympl=0.7.0
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jinja2=3.0.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - notebook=6.4.6
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=21.3
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pathspec=0.7.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - python=3.8.12
  - python-dateutil=2.8.2
  - pyzmq=22.3.0
  - qt=5.9.7
  - readline=8.1
  - regex=2021.8.3
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - pandas==1.3.5
    - progressbar==2.5
    - pytz==2021.3
    - scipy==1.7.3
